export const SET_ALERT_TYPE = "SET_ALERT";
export const SET_PAGE_IS_ROUTING_TYPE = "SET_PAGE_IS_ROUTING";
export const TOGGLE_SHOW_MODAL_TYPE = "TOGGLE_SHOW_MODAL";
export const GLOBAL_ERROR_TYPE = "GLOBAL_ERROR";
