export const PROJECT_LOADING_TYPE = "PROJECT_LOADING";
export const PROJECT_ERROR_TYPE = "PROJECT_ERROR";
export const GET_ALL_PROJECTS_TYPE = "GET_ALL_PROJECTS";
export const GET_SINGLE_PROJECT_TYPE = "GET_SINGLE_PROJECT";
export const EDIT_PROJECT_TYPE = "EDIT_PROJECT";
export const DELETE_PROJECT_TYPE = "DELETE_PROJECT";
